---
classes:
  - '::fuel_project::common'
  - '::fuel_project::jenkins::slave'
  - '::fuel_project::jenkins::slave::infra'
  - '::sysctl::base'

fuel_project::common::external_host: true
fuel_project::jenkins::slave::verify_jenkins_jobs: true

devopslib::downloads_cleaner::clean_seeds: true
devopslib::downloads_cleaner::cleanup_dirs:
  -
    dir: '/var/www/seed/fuelweb-iso'
    ttl: 10
    pattern: 'fuel-*'
  -
    dir: '/srv/downloads'
    ttl: 1
    pattern: '*'

jenkins::slave::authorized_keys:
  'jenkins@infra-ci.fuel-jenkins.org':
    type: ssh-rsa
    key: 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDjKXfSRWlFvlqSQErc5T9ZpLKLY6kPOJiKs8qmJZtqQ5yAU9nSBfQrPQaxj5lgoEscFVxzBOq6igh/MWcUU2nxDeKpHunfcA/w08Rq1jD0TGDBFjE0oyWAa9N9bGa5n/Fx/WDGz70+1BLfVkg+RFVQecTZkb0glC3eTkWOCF9sSdLYdalO6x1R1JvUQ/rp83eZzP6J09FoZUxrQPOeW6YtvF9Mh0xS2+y7zt/dVBDqucvgMkNyUOZMPKx42iUUtXemQCgrCsKWtFankRbEsCE2HGv+tWCa3HnKu9/XkFqjo5RU5Gn3z7/t7QT1AZzFFbXweBpjSW0A0y42ILvug1En'

sysctl::base::values:
  fs.inotify.max_user_instances:
    value: 256
  net.ipv4.ip_forward:
    value: '1'
  net.ipv4.tcp_syncookies:
    value: 1
  net.ipv4.tcp_window_scaling:
    value: 1
  net.ipv4.tcp_congestion_control:
    value: cubic
  net.ipv4.tcp_no_metrics_save:
    value: 1
  net.ipv4.tcp_moderate_rcvbuf:
    value: 1
