---
classes:
  - '::fuel_project::jenkins::slave'
  - '::sudo'
  - '::sysctl::base'

fuel_project::common::ssh_keys_group: 'ci_team'

fuel_project::jenkins::slave::verify_network_checker: true
fuel_project::jenkins::slave::install_docker: true
fuel_project::jenkins::slave::docker_config: |
    {
      "registry.domain.org": {
        "auth": "someMagicalAuthorization==",
        "email": "jenkins@mirantis.net"
      }
    }

devopslib::downloads_cleaner:
  -
    dir: '/var/www/fuelweb-iso'
    ttl: 10
    pattern: 'fuel-*'
  -
    dir: '/srv/downloads'
    ttl: 1
    pattern: 'fuel-*'

# keep current sudo configuration
sudo::purge: false
sudo::config_file_replace: false

# https://bugs.launchpad.net/fuel/+bug/1458842
sudo::configs:
  'tcpdump':
    'content': '%sudo ALL=(ALL) NOPASSWD: /usr/sbin/tcpdump'
  'dutop':
    'content': '%sudo ALL=(ALL) NOPASSWD: /usr/bin/dutop ""'
  'dutop-libvirt':
    'content': '%sudo ALL=(ALL) NOPASSWD: /usr/bin/dutop /var/lib/libvirt'


devopslib::downloads_cleaner::clean_seeds: true
devopslib::downloads_cleaner::cleanup_dirs:
  -
    dir: '/var/www/seed/fuelweb-iso'
    ttl: 10
    pattern: 'fuel-*'
  -
    dir: '/srv/downloads'
    ttl: 1
    pattern: '*'

# apparmor rules
fuel_project::common::apparmor:
  /usr/sbin/libvirtd:
    ensure: disabled
  /usr/lib/libvirt/virt-aa-helper:
    ensure: disabled

# enable hugepages
fuel_project::common::kernel_parameters:
  transparent_hugepage:
    value: never
  hugepagesz:
    value: 1G
    require: Kernel_parameter[transparent_hugepage]
  hugepages:
    value: 256
    require: Kernel_parameter[hugepagesz]
  default_hugepagesz:
    value: 1G
    require: Kernel_parameter[hugepages]

fuel_project::common::files:
  /hugepages:
    ensure: directory

fuel_project::common::mounts:
  /hugepages:
    ensure: mounted
    atboot: true
    device: hugetlbfs
    fstype: hugetlbfs
    options: mode=1777
    require: File[/hugepages]
