# image:ci-xenial-server-cloudimg-amd64
---
classes:
  - '::fuel_project::apps::lpreports'
  - '::fuel_project::common'
  - '::fuel_project::nginx'
  - '::lpreports::webapp'
  - '::mongodb::client'
  - '::mongodb::server'

fuel_project::apps::lpreports::config_repo: 'ssh://lpreports@review.fuel-infra.org/tools/lpreports'
fuel_project::apps::lpreports::ssh_key_contents: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEA1bg7U9h93FRFFzRjfMNb2hQLytHxVUNrNvM+LD0sgyJc65CG
  aZg3LLG871xfbWEa+Lpld1Tr5mPA9Kd2xNWJFG3kxtjMbBeUibLf9pzxFvSeEI8E
  squC5gfL0z0OXUWguaqbHqNk0dye1tKSNZx+oj63lGIYEjE+JDzeVu+NRkCxeBDs
  aM9eqjXmE/n9fRmsgwLAUXePv/O+RLy5PSzYHQTZSm0mZ85Fu8945GeR9dRfzbK0
  XRNsafY3f97A7MudRxi1hVHkR3xV43n3bsRDMrDb3lWPhi2d4HWqQ0E8k9wD+5Km
  igXjGvDzHBrz03iPsjO4OmRVVEsMqvypmyJGEwIDAQABAoIBAFKLNV7M3s+aPJUZ
  xtMJIRC5bVSIgY1M3Lv8dqbfebGsM/dHeqKOB8FbZH2OT80PFDu8wjO0uOfi30Oe
  6mBbmPYq+5FRaqLU+Km2TIoTU4pqMCJ1GntngscVe8O6cTHVEp6jJgZPVUE41KBj
  89SA/OftETpeKK3eFwIoADfTjdzzquf0QmTHW9VaDXRsWGfXU6wBTMH9o+XY9lY6
  VshnX5Hmoaw+DfIuoX/Zv2poU+f5ghcrpLhlfY29zaLYpncHQYbayGpi9iM5R1yP
  KapXMeaj3Kf3vW0DXpv9LS0Hfu0dcS2BGJgrGcrfecWlzITw6UgF/FtyIWRQL1UK
  edAqrwECgYEA6x/sg7onqq2AYA0qQgxGpRS5PTISsYoULVbfUBh/byTw6/y4YMq4
  fVJls1FZ7J0fXit5uIogvWsk5ePa7he/pE85XUxY0qZwNN5AvGHwi1kljPSpvBmo
  KO72MWpiNzI3RvOEOq6m6LQ5Yh64uIoz6gCGgxRKIDDVeJ94oTN1lD0CgYEA6LHM
  mPmkIwd91DOJX1KRDTj/eLubgPdxPj9A9eY7uz3r69FuRufhekSQ8JOfTSa7DcNr
  MIlg0rma/m1Y2NKke5OUwLTP9g6bEjxWnnk88IJDwBFF0w1c4lcp8Crd7d7t5gXt
  /tuoQ1JlUIiNvUf/5DpsHImjI8Iwca+qEn312I8CgYEAjnvrFSyjSyAXUp3HxPyx
  duqnErmccHBvp8YkT+J4nz7wrOGaTjWrNW7QaKlc6DGTR7rq6XTzQDaExrec/Xnw
  zb6g0bQpg4YPK0qgSkjDv35HbjL6BR47NIsTMID6gd5xdxKtR+59ATnuKFLbuCEw
  Mpcc7KRIA1f0lUN2k6GemDUCgYBHzpZUnrUIGke6NC0wPUqFyhEMMNjL84/+pYZm
  W6YTIgirvPVK7EOod4BCvUtrg4g1txhc4gf+/0fVO+ku/9HCUMiWrzV9uQQhnH0e
  aktj7M77dlkVyAnhzwQiGRhjT2gak7nd6+sA22xobbtPrehJhb3XEKJHZqWMb6kM
  C9LSAQKBgGTNpYWdvgmAboxbClwllmEluaga9vJA2oXi3z93wKRv+frnI2cYGQvY
  OjI0MatW4vD7Z46Bv0+r9FoRYugd8cOQKegMu9ECVx5fPChPbttnA46s8KH5OpEj
  K9rn3wvcclXbYWphPdKpF8HK+vR+1TFSarfhFfrUHyCBol4Bt3lT
  -----END RSA PRIVATE KEY-----

lpreports::webapp::config:
  SECRET_KEY: 'SECRET_KEY'
  GOOGLE_ID: 'GOOGLE_ID'
  GOOGLE_SECRET: 'GOOGLE_SECRET'
  LP_CONSUMER_KEY: 'LP_CONSUMER_KEY'
  LP_TOKEN: 'LP_TOKEN'
  LP_SIGNATURE: 'LP_SIGNATURE'
  MONGO_BUGS_URI: 'mongodb://127.0.0.1/lpreports?journal=true'
  MONGO_AREA_TAGS_URI: 'mongodb://127.0.0.1/lpreports?journal=true'
  MONGO_ASSIGNEES_URI: 'mongodb://127.0.0.1/lpreports?journal=true'
  MONGO_USERS_URI: 'mongodb://127.0.0.1/lpreports?journal=true'
  MONGO_SECURITY_URI: 'mongodb://127.0.0.1/lpreports?journal=true'
  MONGO_CVE_URI: 'mongodb://127.0.0.1/lpreports?journal=true'
  MONGO_BUGS_CONNECT: false
  MONGO_AREA_TAGS_CONNECT: false
  MONGO_ASSIGNEES_CONNECT: false
  MONGO_USERS_CONNECT: false
  MONGO_SECURITY_CONNECT: false
  MONGO_CVE_CONNECT: false

lpreports::webapp::nginx_log_format: 'proxy'
lpreports::webapp::nginx_server_name: 'lpreports.test.local'
lpreports::webapp::ssl_certificate_contents: |
  -----BEGIN CERTIFICATE-----
  MIIDmTCCAoGgAwIBAgIJAJGc54yYKZs8MA0GCSqGSIb3DQEBCwUAMGMxCzAJBgNV
  BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
  aWRnaXRzIFB0eSBMdGQxHDAaBgNVBAMME3JlZ2lzdHJ5LnRlc3QubG9jYWwwHhcN
  MTUwODIwMDgxMDMwWhcNMTYwODE5MDgxMDMwWjBjMQswCQYDVQQGEwJBVTETMBEG
  A1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkg
  THRkMRwwGgYDVQQDDBNyZWdpc3RyeS50ZXN0LmxvY2FsMIIBIjANBgkqhkiG9w0B
  AQEFAAOCAQ8AMIIBCgKCAQEApY41bO7rbYG0TGKlMQVCd7NEQ/HSn1mZjtQyWdUy
  orh7RpSN6g7Q5c9diLmv2+dzbJzNldL9/r5hiA5zz/7qnWUNU9+9Kl6JRq7RWUoy
  aMoqtOjx+qUQSuYV966ZbIygcQb2iT20gVogGQTb0qx72mXj7YVD1WDgkl2MpUyt
  8R9b7SfulBodK4mO3G+N5Ym2Ebo/EkaBhUPo9ErHFbKu1gQNq+tvDfVi2Aqwtiue
  5FHezU1v6BsFgp+/W4Ojw+69WUt1TZhI5sqlhPLGZDpEgFBJnBz03p2gZJ70HPWZ
  SwUMtmhct7qH4wT8khGtPrmHDFB7f+l84YBHrHMBSNM09wIDAQABo1AwTjAdBgNV
  HQ4EFgQUQLMQy8btaVq/Zjpn2qZ4/5H6VFcwHwYDVR0jBBgwFoAUQLMQy8btaVq/
  Zjpn2qZ4/5H6VFcwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAK3Ms
  cJh0eSYNYZ6CnIFWwfuECdpeqhyK/JfnpILQ8lXhxGDxKmjELyy7NFcB+z+cLOju
  42X4VG1XERNS2kk+SaD25nybUi6dm57kMwe6e43kaxrFxu8BGVOMmseyJV5VgM60
  nMkSOCGOOi13WuZZ5E3/dmEVqRmEZr5HZdhGftXZO6MASpteTSnwrSlFJq9FTyhH
  NaY5XIlgajAtAsO2PvZ/nK8CQaR4NELXP2g+iGydlvgkpz3ZZw1ZGNuScLW5tk3y
  LACfM+QTWd1JlWInSAcpJ/5oyeiPghF+RyewE7Q5ohAPi1dJBTOHFBaGc7guSJvn
  hBrtuTHuW16PtQHgeQ==
  -----END CERTIFICATE-----

lpreports::webapp::ssl_key_contents: |
  -----BEGIN PRIVATE KEY-----
  MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCljjVs7uttgbRM
  YqUxBUJ3s0RD8dKfWZmO1DJZ1TKiuHtGlI3qDtDlz12Iua/b53NsnM2V0v3+vmGI
  DnPP/uqdZQ1T370qXolGrtFZSjJoyiq06PH6pRBK5hX3rplsjKBxBvaJPbSBWiAZ
  BNvSrHvaZePthUPVYOCSXYylTK3xH1vtJ+6UGh0riY7cb43libYRuj8SRoGFQ+j0
  SscVsq7WBA2r628N9WLYCrC2K57kUd7NTW/oGwWCn79bg6PD7r1ZS3VNmEjmyqWE
  8sZkOkSAUEmcHPTenaBknvQc9ZlLBQy2aFy3uofjBPySEa0+uYcMUHt/6XzhgEes
  cwFI0zT3AgMBAAECggEABa0didGbQtLqop/TOB4NDFuaIJY++XWx/SKrY0cbCFc4
  6s+XGgpOAUMd2t06+VgzLesmZVepm71dTLPqJpx/4MuhLFoEe1pobIL77IrNtagQ
  1MkT2tsj9t1yrV5QJlef/KAXfdcexDyZ0yHGg6+kQ3Ww3ejuzXcX3AzXEKfTYuv5
  NSD4MxFomkA64+IcCI49IXsXFshk3oL0LiWhaWgHWzA0RyhLwndyXyVMiCl99uVP
  ZAN7U965mv+AtsaChg/1K87AR7e6+ZxfmKuTAoJCU4xcgMVUntC1nXigDok+9IAa
  Pfx4k5JoaFz7wjyxui1qWtKaPnq5d4JhtSdBTIrwGQKBgQDSOzMk2Ul2XYm3omag
  kGAOFW+bdvRdYrnUA54ycQDLELhXN7mOypIBNMe72q+oU8Y5BmPgJS5iGIXORWK6
  BluCsRZJwJsG8Hv5X4NEPNk21TSJeCdUNcyEzNPUVInQ/oZrsP908w27CwjpU6oW
  Wh9vsngZbyy1oAGvwwO+BcmFywKBgQDJmRlvm2pELizTrpXA8DCkQf3JGqOj+Yt7
  68v2Kbbt/+fbcJj96XljZKNDh75BfHZsjCOgeBEKqpK9cdEDprv9RpQtbyN1iI2m
  5obmhDOAE2O/jkZb8XdlZhe9GfXPKdp8U17Qv+RJR+7YblFDZasBkDHPbbUms8iC
  UXToXnfIBQKBgQCST+cxTxREj6boKdt5BeIEC0EolqpNUAd6maYA/wqJSTKyaLL4
  wNzKgBw+Dl3QLbW4PE1IUzgrx1tgioPCaehIVczoOWbrdnUhwiqOVDbsZYfx4LCm
  d+bFyfPnQ4rC7FFLI902XG4C7hQepz6p3cEhMLlLIkeghCKIW5YAKvDs7wKBgCry
  zPJz/72qwK4QQaMrCJHV5UVUwYwLe+XYpEk7Ndeab0DWyiE9/jholkeqwaOd6nTR
  nj1vluHY2Q43Ezpd6SraQHM1fC5r+xGVhyPRAk/E0blbjC3GUZNunpwQzcdmuT9H
  W6nJV88s3fuJ9RIQtM/Ocm4ohzFJl+v7gpaGmaopAoGBAIGV5cMTHADemhoPPGsC
  EkkuUTgT14WteC+s/ks0k3j/Ya3LxodukZ++gLlp+XDC8dU1U6+34zXFapAzs5AY
  FrGQnprUJC2djN9JPlOxa/X2Bl4OEJUkTWALFY5uLXQyKA8fH2nkxiypXnil41Rd
  IMjK3YBsHDrVQ9xjRF5NhF5Z
  -----END PRIVATE KEY-----

mongodb::server::bind_ip: ['127.0.0.1']
mongodb::server::dbpath: '/var/lib/mongodb'
mongodb::server::directoryperdb: true
mongodb::server::keyfile:
mongodb::server::keyfile_content:
mongodb::server::noauth: true
mongodb::server::nohttpinterface: true
mongodb::server::port: 27017
mongodb::server::rest: false
mongodb::server::verbose: true

uwsgi::application::buffer_size: 65535
