---
classes:
  - '::fuel_project::jenkins::slave'
  - '::fuel_project::apps::seed'

fuel_project::apps::seed::shares:
  mirror:
    service_fqdn:
      - 'mirror.example.com'
      - "%{::fqdn}"
    path: '/var/www/mirror'
    http_ro: true
    rsync_ro: true
    rsync_rw: true
    username: jenkins

rsync::server::use_xinetd: false
