---
classes:
  - '::fuel_project::common'
  - '::nodepool'
  - '::os_client_config'
  - '::fuel_project::nodepool'

# Enable periodic puppet agent run to update Nodepool configuration
fuel_project::common::puppet_cron_ok: 'YES, I KNOW WHAT I AM DOING, REALLY.'
fuel_project::common::puppet_cron:
  hour: '*'
  minute: '15'

# General parameters
# Not required for nodepool module, but used by other modules
nodepool::nodepool_user: 'nodepool'
nodepool::nodepool_group: 'nodepool'
nodepool::nodepool_home: '/var/lib/nodepool'

nodepool::environment:
  'NODEPOOL_SSH_KEY':
    'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNWgMf6IisSY0HK0mpHkgVhRxHsDom81PJ6W3jAgcSBWY1Kz/2vL98SK91ppgYmnDa2uLbchY2Xk9ciefMpm7Qq5EO6oSPKJJhADyCYAX/7YomZIy4Xu7HxEh0Z6VCLt0DymwN4tBS9JuTISvEm17BLgtis/AemA2eRIl0JAdPf9rmQps4KP5AhG60ucdtTKD0y8TFK95ateplgcq9JLRInhrdg/vnJLbKnV7lP1g5dfY1rm6bum7P+Jwf2tdTOa0b5ucK/+iWVbyPO4Z2afPpblh4Vynfe2wMzzpGAp3n5MwtH2EZmSXm/B6/CkgOFROsmWH8MzQEvNBGHhw+ONR9'

# Clouds configuration
os_client_config::cloud_configs:
  global_profiles:
    profiles: true
    clouds:
      some-profile:
        auth:
          auth_url: 'http://keystone.domain.tld:5000/v3'
        identity_api_version: '3'
  nodepool_clouds:
    user: "%{hiera('nodepool::nodepool_user')}"
    home: "%{hiera('nodepool::nodepool_home')}"
    cache:
      expiration_time: 3600
    clouds:
      some-cloud:
        profile: 'some-profile'
        region_name: 'RegionOne'
  nodepool_private:
    user: "%{hiera('nodepool::nodepool_user')}"
    home: "%{hiera('nodepool::nodepool_home')}"
    secure: true
    clouds:
      some-cloud:
        auth:
          username: 'cloud-user'
          password: 'cloud-password'
          project_name: 'nodepool'
          domain_id: 'default'

# Database
fuel_project::nodepool::db_name: 'nodepool'
fuel_project::nodepool::db_user: 'nodepool'
fuel_project::nodepool::db_pass: 'N0depoo1'

# Jenkins(-es)
fuel_project::nodepool::jenkins_targets:
  jenkins-server:
    url: 'https://jenkins.donain.tld/'
    user: 'jenkins'
    apikey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    credentials: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'

# SSH private key to be used for accessing VMs
fuel_project::nodepool::vm_ssh_private_key_contents: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpQIBAAKCAQEAvH4Y+FA345hwv1mQw7A8y6VpgVWzK66XqgmC4nHCb34DPSCH
  2hgo0xk5UXb9L1EjlB9IaSuj/ANa8LvTeEXJ4fQcvzjgq96pnAyTsFeHvcNpgQTU
  4+JcxXOMo8L0xvXh95J0PLVm356JqBPIKph6Df6QNuhrr6JzZPxz/uAyuTwEMq3p
  uR6auod583/5hACiAYxNp8SUfMgbCxyne20nhTwk8ok0CU/od+it6TcIJbNbbAIn
  IvzDKI49H4Ax4A0ucb877AHnq8+8wn3H4DUn2R6+J4sIgLaRZPtTE3OH33Fp3SqE
  S5wTt1xk3yeSz8FMqVMIfhBc2+/Iydaohf0A9QIDAQABAoIBAQCzVcHKFwBlsTas
  R7ndBUOCedlcrT3vtIglxjDZ42QbkafhM58tWEkXN2t6X5xZtXgFSJIrRdMaRdLz
  MbDsQHHoYcosASB5RTrX9ntZjp3eZRpvHzqxqj+buOk5MZaT6YLZemTPEcRTw9Gy
  sUeDh1ixEd8B7rXt/8CMd0ihWYvJAXfMoHKqsrBi1TgSpOXBF9X/dWtPiAKPHuwm
  Gu8Ek0NtvbvYp+64hLh6rucGNz00EZK3OG9JQLMUX+Ps0BNFrPma2+oY+4VLpUvG
  /bk0xdLUZMHA/S5fcH5r7K/6iyQaJbLCErWuZx9A7k3noWlBR87pSNffqSmCYE+T
  Yl4jFobhAoGBAOIecvivNtB0ribjAuViwSpit0qXbUNf6fVa8nRwB+D+CCljNM5n
  0Wf66enIT/X9QRB0lrsPSI0X02NQC8S1fmt7KDiyfAVbz8Fp/ZL+0hQBZJlpJKXW
  dZwzfJOTsIGLt8orEIXRCaUsxTLwWs5FfrZrNc5grdz8erDaZoowxhztAoGBANVm
  wcyBhsCp2RDyjescPJF8IBB3A5b+npHs6niMDaxPuxn8PLr+aVuX2lJIRD4zxERr
  NwYRsTZzc1VKCZFy7mCG1f1L6vsHImj9fRkHm0CzQAQc7+LvfwYIdFtl6o0jouhY
  oypAumwcUII2At1FC/O+ldR8QyGv2VRF9fcAvvspAoGBAKwXbH0kLN2dz+U8pLmb
  3VO66bDVaoz6dH8NhrVjhjuQWvnUzR3CGbe/WUNZ9rFK27gAY69eRGNNnM5a33oI
  f3yhsMzl2knhxE55skmrsosTPFMdmIy2mbAV51wR7SXLBkfRWrPdki+p0TOhhhqy
  /WssUTkOj4Q+i8oJjjziPgVJAoGBAI9Pzt50Lfa9GdVTzxMRh2t8nFvyUSraG8uL
  +3qxM42AjfpJds9tg3vLYwbXGV1cjnYUOoOM5iHXLqEcc4iGUqfoZVUR4uBqTiWL
  9rMUdKLivh8E/+S7SebXTq0CqJ3YTNMUk58QkSGBcl+/vfSzJe+vEhf8y2iYG6+I
  vEIA8kDhAoGAdsdM4Ox9uVvHC2UUOJZDsYYeTkQjCmLA+L8ZpeZ/br1Dg724nuXz
  7t1u65QgqmJcnxgXid5YZWshak7xTxSJS8her6Sd8qNPr8tXYMXlZUK2BJp9A0xT
  oJzQZfokXhqAQAYOQWmie7aIOwVnvj3QJ5cCbV8ktwvEbZ/go0OAH4A=
  -----END RSA PRIVATE KEY-----

# project-config parameters
project_config::url: 'ssh://user@gerrit.domain.tld:29418/openstack-infra/project-config'
project_config::revision: 'some-branch'

fuel_project::nodepool::project_config_ssh_private_key_contents: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpQIBAAKCAQEAvH4Y+FA345hwv1mQw7A8y6VpgVWzK66XqgmC4nHCb34DPSCH
  2hgo0xk5UXb9L1EjlB9IaSuj/ANa8LvTeEXJ4fQcvzjgq96pnAyTsFeHvcNpgQTU
  4+JcxXOMo8L0xvXh95J0PLVm356JqBPIKph6Df6QNuhrr6JzZPxz/uAyuTwEMq3p
  uR6auod583/5hACiAYxNp8SUfMgbCxyne20nhTwk8ok0CU/od+it6TcIJbNbbAIn
  IvzDKI49H4Ax4A0ucb877AHnq8+8wn3H4DUn2R6+J4sIgLaRZPtTE3OH33Fp3SqE
  S5wTt1xk3yeSz8FMqVMIfhBc2+/Iydaohf0A9QIDAQABAoIBAQCzVcHKFwBlsTas
  R7ndBUOCedlcrT3vtIglxjDZ42QbkafhM58tWEkXN2t6X5xZtXgFSJIrRdMaRdLz
  MbDsQHHoYcosASB5RTrX9ntZjp3eZRpvHzqxqj+buOk5MZaT6YLZemTPEcRTw9Gy
  sUeDh1ixEd8B7rXt/8CMd0ihWYvJAXfMoHKqsrBi1TgSpOXBF9X/dWtPiAKPHuwm
  Gu8Ek0NtvbvYp+64hLh6rucGNz00EZK3OG9JQLMUX+Ps0BNFrPma2+oY+4VLpUvG
  /bk0xdLUZMHA/S5fcH5r7K/6iyQaJbLCErWuZx9A7k3noWlBR87pSNffqSmCYE+T
  Yl4jFobhAoGBAOIecvivNtB0ribjAuViwSpit0qXbUNf6fVa8nRwB+D+CCljNM5n
  0Wf66enIT/X9QRB0lrsPSI0X02NQC8S1fmt7KDiyfAVbz8Fp/ZL+0hQBZJlpJKXW
  dZwzfJOTsIGLt8orEIXRCaUsxTLwWs5FfrZrNc5grdz8erDaZoowxhztAoGBANVm
  wcyBhsCp2RDyjescPJF8IBB3A5b+npHs6niMDaxPuxn8PLr+aVuX2lJIRD4zxERr
  NwYRsTZzc1VKCZFy7mCG1f1L6vsHImj9fRkHm0CzQAQc7+LvfwYIdFtl6o0jouhY
  oypAumwcUII2At1FC/O+ldR8QyGv2VRF9fcAvvspAoGBAKwXbH0kLN2dz+U8pLmb
  3VO66bDVaoz6dH8NhrVjhjuQWvnUzR3CGbe/WUNZ9rFK27gAY69eRGNNnM5a33oI
  f3yhsMzl2knhxE55skmrsosTPFMdmIy2mbAV51wR7SXLBkfRWrPdki+p0TOhhhqy
  /WssUTkOj4Q+i8oJjjziPgVJAoGBAI9Pzt50Lfa9GdVTzxMRh2t8nFvyUSraG8uL
  +3qxM42AjfpJds9tg3vLYwbXGV1cjnYUOoOM5iHXLqEcc4iGUqfoZVUR4uBqTiWL
  9rMUdKLivh8E/+S7SebXTq0CqJ3YTNMUk58QkSGBcl+/vfSzJe+vEhf8y2iYG6+I
  vEIA8kDhAoGAdsdM4Ox9uVvHC2UUOJZDsYYeTkQjCmLA+L8ZpeZ/br1Dg724nuXz
  7t1u65QgqmJcnxgXid5YZWshak7xTxSJS8her6Sd8qNPr8tXYMXlZUK2BJp9A0xT
  oJzQZfokXhqAQAYOQWmie7aIOwVnvj3QJ5cCbV8ktwvEbZ/go0OAH4A=
  -----END RSA PRIVATE KEY-----
