---
classes:
  - '::fuel_project::common'
  - '::jenkins::slave'
  - '::fuel_project::roles::perestroika::builder'

fuel_project::common::kernel_package: 'linux-image-extra-3.19.0-26-generic'
fuel_project::roles::perestroika::builder::docker_package: 'lxc-docker-1.6.1'

fuel_project::common::known_hosts:
  'jenkins':
    hosts:
     'review.fuel-infra.org':
       port: 29418
     'review.openstack.org':
       port: 29418
     'gerrit.mirantis.com':
       port: 29418
