---
classes:
  - '::fuel_project::common'
  - '::mysql::server'

mysql::client::package_name: 'mariadb-client'
mysql::server::package_name: 'mariadb-server'
mysql::server::override_options:
  mysqld:
    bind_address: '0.0.0.0'
    innodb_buffer_pool_size: '1G'
    innodb_file_per_table: 1
    innodb_file_format: 'barracuda'
    innodb_flush_method: 'O_DIRECT'
    join_buffer_size: '512M'
    lock_wait_timeout: 120
    log_queries_not_using_indexes: 1
    max_connections: 1024
    query_cache_size: '128M'
    query_cache_type: 1
    read_rnd_buffer_size: '8M'
    slow_query_log: 1
    slow_query_log_file: '/var/log/mysql/slow.log'
    sort_buffer_size: '4M'
    table_open_cache: '256M'
    thread_cache_size: '4M'
